import './globals.css'
import { Inter } from 'next/font/google'
import { getServerSession } from 'next-auth'
import { Toaster } from '@/components/ui/toaster'
import NextAuthProvider from '@/components/custom/providers/NextAuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Santa Casa',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

  const session = await getServerSession()

  return (
    <html lang="pt-BR">

      <body className={inter.className}>
        <NextAuthProvider session={session}>
          <Toaster />
          <main>
            {children}
          </main>
        </NextAuthProvider>

      </body>
    </html>
  )
}